//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftResBusiness.RolWSClient {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class rolDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool esClienteField;
        
        private bool esClienteFieldSpecified;
        
        private int idRolField;
        
        private bool idRolFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool esCliente {
            get {
                return this.esClienteField;
            }
            set {
                this.esClienteField = value;
                this.RaisePropertyChanged("esCliente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool esClienteSpecified {
            get {
                return this.esClienteFieldSpecified;
            }
            set {
                this.esClienteFieldSpecified = value;
                this.RaisePropertyChanged("esClienteSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idRol {
            get {
                return this.idRolField;
            }
            set {
                this.idRolField = value;
                this.RaisePropertyChanged("idRol");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idRolSpecified {
            get {
                return this.idRolFieldSpecified;
            }
            set {
                this.idRolFieldSpecified = value;
                this.RaisePropertyChanged("idRolSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softres.pucp.edu.pe/", ConfigurationName="RolWSClient.Rol")]
    public interface Rol {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Rol/insertarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Rol/insertarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.RolWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Rol/insertar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.RolWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Rol/insertar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.RolWSClient.insertarResponse insertar(SoftResBusiness.RolWSClient.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Rol/insertarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Rol/insertarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.insertarResponse> insertarAsync(SoftResBusiness.RolWSClient.insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Rol/obtenerPorIdRequest", ReplyAction="http://services.softres.pucp.edu.pe/Rol/obtenerPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.RolWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Rol/obtenerPorId/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.RolWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Rol/obtenerPorId/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.RolWSClient.obtenerPorIdResponse obtenerPorId(SoftResBusiness.RolWSClient.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Rol/obtenerPorIdRequest", ReplyAction="http://services.softres.pucp.edu.pe/Rol/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.obtenerPorIdResponse> obtenerPorIdAsync(SoftResBusiness.RolWSClient.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Rol/listarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Rol/listarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.RolWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Rol/listar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.RolWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Rol/listar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.RolWSClient.listarResponse listar(SoftResBusiness.RolWSClient.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Rol/listarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Rol/listarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.listarResponse> listarAsync(SoftResBusiness.RolWSClient.listarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Rol/eliminarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Rol/eliminarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.RolWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Rol/eliminar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.RolWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Rol/eliminar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.RolWSClient.eliminarResponse eliminar(SoftResBusiness.RolWSClient.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Rol/eliminarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Rol/eliminarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.eliminarResponse> eliminarAsync(SoftResBusiness.RolWSClient.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Rol/modificarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Rol/modificarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.RolWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Rol/modificar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.RolWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Rol/modificar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.RolWSClient.modificarResponse modificar(SoftResBusiness.RolWSClient.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Rol/modificarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Rol/modificarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.modificarResponse> modificarAsync(SoftResBusiness.RolWSClient.modificarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.RolWSClient.rolDTO arg0;
        
        public insertarRequest() {
        }
        
        public insertarRequest(SoftResBusiness.RolWSClient.rolDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.RolWSClient.rolDTO @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(SoftResBusiness.RolWSClient.rolDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRequest {
        
        public listarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.RolWSClient.rolDTO[] @return;
        
        public listarResponse() {
        }
        
        public listarResponse(SoftResBusiness.RolWSClient.rolDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.RolWSClient.rolDTO arg0;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(SoftResBusiness.RolWSClient.rolDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.RolWSClient.rolDTO arg0;
        
        public modificarRequest() {
        }
        
        public modificarRequest(SoftResBusiness.RolWSClient.rolDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarResponse() {
        }
        
        public modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface RolChannel : SoftResBusiness.RolWSClient.Rol, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class RolClient : System.ServiceModel.ClientBase<SoftResBusiness.RolWSClient.Rol>, SoftResBusiness.RolWSClient.Rol {
        
        public RolClient() {
        }
        
        public RolClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public RolClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public RolClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.RolWSClient.insertarResponse SoftResBusiness.RolWSClient.Rol.insertar(SoftResBusiness.RolWSClient.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(SoftResBusiness.RolWSClient.rolDTO arg0) {
            SoftResBusiness.RolWSClient.insertarRequest inValue = new SoftResBusiness.RolWSClient.insertarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.RolWSClient.insertarResponse retVal = ((SoftResBusiness.RolWSClient.Rol)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.insertarResponse> SoftResBusiness.RolWSClient.Rol.insertarAsync(SoftResBusiness.RolWSClient.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.insertarResponse> insertarAsync(SoftResBusiness.RolWSClient.rolDTO arg0) {
            SoftResBusiness.RolWSClient.insertarRequest inValue = new SoftResBusiness.RolWSClient.insertarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.RolWSClient.Rol)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.RolWSClient.obtenerPorIdResponse SoftResBusiness.RolWSClient.Rol.obtenerPorId(SoftResBusiness.RolWSClient.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public SoftResBusiness.RolWSClient.rolDTO obtenerPorId(int arg0) {
            SoftResBusiness.RolWSClient.obtenerPorIdRequest inValue = new SoftResBusiness.RolWSClient.obtenerPorIdRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.RolWSClient.obtenerPorIdResponse retVal = ((SoftResBusiness.RolWSClient.Rol)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.obtenerPorIdResponse> SoftResBusiness.RolWSClient.Rol.obtenerPorIdAsync(SoftResBusiness.RolWSClient.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.obtenerPorIdResponse> obtenerPorIdAsync(int arg0) {
            SoftResBusiness.RolWSClient.obtenerPorIdRequest inValue = new SoftResBusiness.RolWSClient.obtenerPorIdRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.RolWSClient.Rol)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.RolWSClient.listarResponse SoftResBusiness.RolWSClient.Rol.listar(SoftResBusiness.RolWSClient.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public SoftResBusiness.RolWSClient.rolDTO[] listar() {
            SoftResBusiness.RolWSClient.listarRequest inValue = new SoftResBusiness.RolWSClient.listarRequest();
            SoftResBusiness.RolWSClient.listarResponse retVal = ((SoftResBusiness.RolWSClient.Rol)(this)).listar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.listarResponse> SoftResBusiness.RolWSClient.Rol.listarAsync(SoftResBusiness.RolWSClient.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.listarResponse> listarAsync() {
            SoftResBusiness.RolWSClient.listarRequest inValue = new SoftResBusiness.RolWSClient.listarRequest();
            return ((SoftResBusiness.RolWSClient.Rol)(this)).listarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.RolWSClient.eliminarResponse SoftResBusiness.RolWSClient.Rol.eliminar(SoftResBusiness.RolWSClient.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(SoftResBusiness.RolWSClient.rolDTO arg0) {
            SoftResBusiness.RolWSClient.eliminarRequest inValue = new SoftResBusiness.RolWSClient.eliminarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.RolWSClient.eliminarResponse retVal = ((SoftResBusiness.RolWSClient.Rol)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.eliminarResponse> SoftResBusiness.RolWSClient.Rol.eliminarAsync(SoftResBusiness.RolWSClient.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.eliminarResponse> eliminarAsync(SoftResBusiness.RolWSClient.rolDTO arg0) {
            SoftResBusiness.RolWSClient.eliminarRequest inValue = new SoftResBusiness.RolWSClient.eliminarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.RolWSClient.Rol)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.RolWSClient.modificarResponse SoftResBusiness.RolWSClient.Rol.modificar(SoftResBusiness.RolWSClient.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public int modificar(SoftResBusiness.RolWSClient.rolDTO arg0) {
            SoftResBusiness.RolWSClient.modificarRequest inValue = new SoftResBusiness.RolWSClient.modificarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.RolWSClient.modificarResponse retVal = ((SoftResBusiness.RolWSClient.Rol)(this)).modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.modificarResponse> SoftResBusiness.RolWSClient.Rol.modificarAsync(SoftResBusiness.RolWSClient.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.RolWSClient.modificarResponse> modificarAsync(SoftResBusiness.RolWSClient.rolDTO arg0) {
            SoftResBusiness.RolWSClient.modificarRequest inValue = new SoftResBusiness.RolWSClient.modificarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.RolWSClient.Rol)(this)).modificarAsync(inValue);
        }
    }
}
