//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftResBusiness.ReporteClienteWSClient {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softres.pucp.edu.pe/", ConfigurationName="ReporteClienteWSClient.ReporteCliente")]
    public interface ReporteCliente {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de partes de mensaje () no coincide con el valor predeterminado (http://services.softres.pucp.edu.pe/).
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/ReporteCliente/reporteClienteRequest", ReplyAction="http://services.softres.pucp.edu.pe/ReporteCliente/reporteClienteResponse")]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.ReporteClienteWSClient.reporteClienteResponse reporteCliente(SoftResBusiness.ReporteClienteWSClient.reporteClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/ReporteCliente/reporteClienteRequest", ReplyAction="http://services.softres.pucp.edu.pe/ReporteCliente/reporteClienteResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.ReporteClienteWSClient.reporteClienteResponse> reporteClienteAsync(SoftResBusiness.ReporteClienteWSClient.reporteClienteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteCliente", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class reporteClienteRequest {
        
        public reporteClienteRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="reporteClienteResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class reporteClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public byte[] @return;
        
        public reporteClienteResponse() {
        }
        
        public reporteClienteResponse(byte[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ReporteClienteChannel : SoftResBusiness.ReporteClienteWSClient.ReporteCliente, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReporteClienteClient : System.ServiceModel.ClientBase<SoftResBusiness.ReporteClienteWSClient.ReporteCliente>, SoftResBusiness.ReporteClienteWSClient.ReporteCliente {
        
        public ReporteClienteClient() {
        }
        
        public ReporteClienteClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReporteClienteClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteClienteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReporteClienteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.ReporteClienteWSClient.reporteClienteResponse SoftResBusiness.ReporteClienteWSClient.ReporteCliente.reporteCliente(SoftResBusiness.ReporteClienteWSClient.reporteClienteRequest request) {
            return base.Channel.reporteCliente(request);
        }
        
        public byte[] reporteCliente() {
            SoftResBusiness.ReporteClienteWSClient.reporteClienteRequest inValue = new SoftResBusiness.ReporteClienteWSClient.reporteClienteRequest();
            SoftResBusiness.ReporteClienteWSClient.reporteClienteResponse retVal = ((SoftResBusiness.ReporteClienteWSClient.ReporteCliente)(this)).reporteCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.ReporteClienteWSClient.reporteClienteResponse> SoftResBusiness.ReporteClienteWSClient.ReporteCliente.reporteClienteAsync(SoftResBusiness.ReporteClienteWSClient.reporteClienteRequest request) {
            return base.Channel.reporteClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.ReporteClienteWSClient.reporteClienteResponse> reporteClienteAsync() {
            SoftResBusiness.ReporteClienteWSClient.reporteClienteRequest inValue = new SoftResBusiness.ReporteClienteWSClient.reporteClienteRequest();
            return ((SoftResBusiness.ReporteClienteWSClient.ReporteCliente)(this)).reporteClienteAsync(inValue);
        }
    }
}
