//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftResBusiness.TipoMesaWSClient {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class tipoMesaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoMesaField;
        
        private bool idTipoMesaFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipoMesa {
            get {
                return this.idTipoMesaField;
            }
            set {
                this.idTipoMesaField = value;
                this.RaisePropertyChanged("idTipoMesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoMesaSpecified {
            get {
                return this.idTipoMesaFieldSpecified;
            }
            set {
                this.idTipoMesaFieldSpecified = value;
                this.RaisePropertyChanged("idTipoMesaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softres.pucp.edu.pe/", ConfigurationName="TipoMesaWSClient.TipoMesa")]
    public interface TipoMesa {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/TipoMesa/listarRequest", ReplyAction="http://services.softres.pucp.edu.pe/TipoMesa/listarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.TipoMesaWSClient.IOException), Action="http://services.softres.pucp.edu.pe/TipoMesa/listar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.TipoMesaWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/TipoMesa/listar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.TipoMesaWSClient.listarResponse listar(SoftResBusiness.TipoMesaWSClient.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/TipoMesa/listarRequest", ReplyAction="http://services.softres.pucp.edu.pe/TipoMesa/listarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.listarResponse> listarAsync(SoftResBusiness.TipoMesaWSClient.listarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/TipoMesa/insertarRequest", ReplyAction="http://services.softres.pucp.edu.pe/TipoMesa/insertarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.TipoMesaWSClient.IOException), Action="http://services.softres.pucp.edu.pe/TipoMesa/insertar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.TipoMesaWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/TipoMesa/insertar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.TipoMesaWSClient.insertarResponse insertar(SoftResBusiness.TipoMesaWSClient.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/TipoMesa/insertarRequest", ReplyAction="http://services.softres.pucp.edu.pe/TipoMesa/insertarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.insertarResponse> insertarAsync(SoftResBusiness.TipoMesaWSClient.insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/TipoMesa/eliminarRequest", ReplyAction="http://services.softres.pucp.edu.pe/TipoMesa/eliminarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.TipoMesaWSClient.IOException), Action="http://services.softres.pucp.edu.pe/TipoMesa/eliminar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.TipoMesaWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/TipoMesa/eliminar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.TipoMesaWSClient.eliminarResponse eliminar(SoftResBusiness.TipoMesaWSClient.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/TipoMesa/eliminarRequest", ReplyAction="http://services.softres.pucp.edu.pe/TipoMesa/eliminarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.eliminarResponse> eliminarAsync(SoftResBusiness.TipoMesaWSClient.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/TipoMesa/modificarRequest", ReplyAction="http://services.softres.pucp.edu.pe/TipoMesa/modificarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.TipoMesaWSClient.IOException), Action="http://services.softres.pucp.edu.pe/TipoMesa/modificar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.TipoMesaWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/TipoMesa/modificar/Fault/InterruptedException" +
            "", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.TipoMesaWSClient.modificarResponse modificar(SoftResBusiness.TipoMesaWSClient.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/TipoMesa/modificarRequest", ReplyAction="http://services.softres.pucp.edu.pe/TipoMesa/modificarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.modificarResponse> modificarAsync(SoftResBusiness.TipoMesaWSClient.modificarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/TipoMesa/obtenerPorIdRequest", ReplyAction="http://services.softres.pucp.edu.pe/TipoMesa/obtenerPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.TipoMesaWSClient.IOException), Action="http://services.softres.pucp.edu.pe/TipoMesa/obtenerPorId/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.TipoMesaWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/TipoMesa/obtenerPorId/Fault/InterruptedExcept" +
            "ion", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.TipoMesaWSClient.obtenerPorIdResponse obtenerPorId(SoftResBusiness.TipoMesaWSClient.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/TipoMesa/obtenerPorIdRequest", ReplyAction="http://services.softres.pucp.edu.pe/TipoMesa/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.obtenerPorIdResponse> obtenerPorIdAsync(SoftResBusiness.TipoMesaWSClient.obtenerPorIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRequest {
        
        public listarRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.TipoMesaWSClient.tipoMesaDTO[] @return;
        
        public listarResponse() {
        }
        
        public listarResponse(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0;
        
        public insertarRequest() {
        }
        
        public insertarRequest(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0;
        
        public modificarRequest() {
        }
        
        public modificarRequest(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarResponse() {
        }
        
        public modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.TipoMesaWSClient.tipoMesaDTO @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TipoMesaChannel : SoftResBusiness.TipoMesaWSClient.TipoMesa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TipoMesaClient : System.ServiceModel.ClientBase<SoftResBusiness.TipoMesaWSClient.TipoMesa>, SoftResBusiness.TipoMesaWSClient.TipoMesa {
        
        public TipoMesaClient() {
        }
        
        public TipoMesaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TipoMesaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoMesaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TipoMesaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.TipoMesaWSClient.listarResponse SoftResBusiness.TipoMesaWSClient.TipoMesa.listar(SoftResBusiness.TipoMesaWSClient.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public SoftResBusiness.TipoMesaWSClient.tipoMesaDTO[] listar() {
            SoftResBusiness.TipoMesaWSClient.listarRequest inValue = new SoftResBusiness.TipoMesaWSClient.listarRequest();
            SoftResBusiness.TipoMesaWSClient.listarResponse retVal = ((SoftResBusiness.TipoMesaWSClient.TipoMesa)(this)).listar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.listarResponse> SoftResBusiness.TipoMesaWSClient.TipoMesa.listarAsync(SoftResBusiness.TipoMesaWSClient.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.listarResponse> listarAsync() {
            SoftResBusiness.TipoMesaWSClient.listarRequest inValue = new SoftResBusiness.TipoMesaWSClient.listarRequest();
            return ((SoftResBusiness.TipoMesaWSClient.TipoMesa)(this)).listarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.TipoMesaWSClient.insertarResponse SoftResBusiness.TipoMesaWSClient.TipoMesa.insertar(SoftResBusiness.TipoMesaWSClient.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0) {
            SoftResBusiness.TipoMesaWSClient.insertarRequest inValue = new SoftResBusiness.TipoMesaWSClient.insertarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.TipoMesaWSClient.insertarResponse retVal = ((SoftResBusiness.TipoMesaWSClient.TipoMesa)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.insertarResponse> SoftResBusiness.TipoMesaWSClient.TipoMesa.insertarAsync(SoftResBusiness.TipoMesaWSClient.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.insertarResponse> insertarAsync(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0) {
            SoftResBusiness.TipoMesaWSClient.insertarRequest inValue = new SoftResBusiness.TipoMesaWSClient.insertarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.TipoMesaWSClient.TipoMesa)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.TipoMesaWSClient.eliminarResponse SoftResBusiness.TipoMesaWSClient.TipoMesa.eliminar(SoftResBusiness.TipoMesaWSClient.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0) {
            SoftResBusiness.TipoMesaWSClient.eliminarRequest inValue = new SoftResBusiness.TipoMesaWSClient.eliminarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.TipoMesaWSClient.eliminarResponse retVal = ((SoftResBusiness.TipoMesaWSClient.TipoMesa)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.eliminarResponse> SoftResBusiness.TipoMesaWSClient.TipoMesa.eliminarAsync(SoftResBusiness.TipoMesaWSClient.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.eliminarResponse> eliminarAsync(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0) {
            SoftResBusiness.TipoMesaWSClient.eliminarRequest inValue = new SoftResBusiness.TipoMesaWSClient.eliminarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.TipoMesaWSClient.TipoMesa)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.TipoMesaWSClient.modificarResponse SoftResBusiness.TipoMesaWSClient.TipoMesa.modificar(SoftResBusiness.TipoMesaWSClient.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public int modificar(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0) {
            SoftResBusiness.TipoMesaWSClient.modificarRequest inValue = new SoftResBusiness.TipoMesaWSClient.modificarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.TipoMesaWSClient.modificarResponse retVal = ((SoftResBusiness.TipoMesaWSClient.TipoMesa)(this)).modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.modificarResponse> SoftResBusiness.TipoMesaWSClient.TipoMesa.modificarAsync(SoftResBusiness.TipoMesaWSClient.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.modificarResponse> modificarAsync(SoftResBusiness.TipoMesaWSClient.tipoMesaDTO arg0) {
            SoftResBusiness.TipoMesaWSClient.modificarRequest inValue = new SoftResBusiness.TipoMesaWSClient.modificarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.TipoMesaWSClient.TipoMesa)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.TipoMesaWSClient.obtenerPorIdResponse SoftResBusiness.TipoMesaWSClient.TipoMesa.obtenerPorId(SoftResBusiness.TipoMesaWSClient.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public SoftResBusiness.TipoMesaWSClient.tipoMesaDTO obtenerPorId(int arg0) {
            SoftResBusiness.TipoMesaWSClient.obtenerPorIdRequest inValue = new SoftResBusiness.TipoMesaWSClient.obtenerPorIdRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.TipoMesaWSClient.obtenerPorIdResponse retVal = ((SoftResBusiness.TipoMesaWSClient.TipoMesa)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.obtenerPorIdResponse> SoftResBusiness.TipoMesaWSClient.TipoMesa.obtenerPorIdAsync(SoftResBusiness.TipoMesaWSClient.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.TipoMesaWSClient.obtenerPorIdResponse> obtenerPorIdAsync(int arg0) {
            SoftResBusiness.TipoMesaWSClient.obtenerPorIdRequest inValue = new SoftResBusiness.TipoMesaWSClient.obtenerPorIdRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.TipoMesaWSClient.TipoMesa)(this)).obtenerPorIdAsync(inValue);
        }
    }
}
