//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftResBusiness.MesaWSClient {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class tipoMesaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idTipoMesaField;
        
        private bool idTipoMesaFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idTipoMesa {
            get {
                return this.idTipoMesaField;
            }
            set {
                this.idTipoMesaField = value;
                this.RaisePropertyChanged("idTipoMesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoMesaSpecified {
            get {
                return this.idTipoMesaFieldSpecified;
            }
            set {
                this.idTipoMesaFieldSpecified = value;
                this.RaisePropertyChanged("idTipoMesaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class sedeDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string distritoField;
        
        private bool estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private System.DateTime fechaModificacionField;
        
        private bool fechaModificacionFieldSpecified;
        
        private string horariosField;
        
        private int idSedeField;
        
        private bool idSedeFieldSpecified;
        
        private string nombreField;
        
        private string usuarioCreacionField;
        
        private string usuarioModificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaModificacionSpecified {
            get {
                return this.fechaModificacionFieldSpecified;
            }
            set {
                this.fechaModificacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaModificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string horarios {
            get {
                return this.horariosField;
            }
            set {
                this.horariosField = value;
                this.RaisePropertyChanged("horarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSedeSpecified {
            get {
                return this.idSedeFieldSpecified;
            }
            set {
                this.idSedeFieldSpecified = value;
                this.RaisePropertyChanged("idSedeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string usuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
                this.RaisePropertyChanged("usuarioModificacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class localDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int cantidadMesasField;
        
        private bool cantidadMesasFieldSpecified;
        
        private string direccionField;
        
        private bool estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private System.DateTime fechaModificacionField;
        
        private bool fechaModificacionFieldSpecified;
        
        private int idLocalField;
        
        private bool idLocalFieldSpecified;
        
        private string nombreField;
        
        private sedeDTO sedeField;
        
        private string telefonoField;
        
        private string usuarioCreacionField;
        
        private string usuarioModificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int cantidadMesas {
            get {
                return this.cantidadMesasField;
            }
            set {
                this.cantidadMesasField = value;
                this.RaisePropertyChanged("cantidadMesas");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool cantidadMesasSpecified {
            get {
                return this.cantidadMesasFieldSpecified;
            }
            set {
                this.cantidadMesasFieldSpecified = value;
                this.RaisePropertyChanged("cantidadMesasSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string direccion {
            get {
                return this.direccionField;
            }
            set {
                this.direccionField = value;
                this.RaisePropertyChanged("direccion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaModificacionSpecified {
            get {
                return this.fechaModificacionFieldSpecified;
            }
            set {
                this.fechaModificacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaModificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idLocal {
            get {
                return this.idLocalField;
            }
            set {
                this.idLocalField = value;
                this.RaisePropertyChanged("idLocal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idLocalSpecified {
            get {
                return this.idLocalFieldSpecified;
            }
            set {
                this.idLocalFieldSpecified = value;
                this.RaisePropertyChanged("idLocalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public sedeDTO sede {
            get {
                return this.sedeField;
            }
            set {
                this.sedeField = value;
                this.RaisePropertyChanged("sede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string telefono {
            get {
                return this.telefonoField;
            }
            set {
                this.telefonoField = value;
                this.RaisePropertyChanged("telefono");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string usuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
                this.RaisePropertyChanged("usuarioModificacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class mesaDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int capacidadField;
        
        private bool capacidadFieldSpecified;
        
        private estadoMesa estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private System.DateTime fechaModificacionField;
        
        private bool fechaModificacionFieldSpecified;
        
        private int idMesaField;
        
        private bool idMesaFieldSpecified;
        
        private localDTO localField;
        
        private string numeroMesaField;
        
        private tipoMesaDTO tipoMesaField;
        
        private string usuarioCreacionField;
        
        private string usuarioModificacionField;
        
        private int xField;
        
        private bool xFieldSpecified;
        
        private int yField;
        
        private bool yFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int capacidad {
            get {
                return this.capacidadField;
            }
            set {
                this.capacidadField = value;
                this.RaisePropertyChanged("capacidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool capacidadSpecified {
            get {
                return this.capacidadFieldSpecified;
            }
            set {
                this.capacidadFieldSpecified = value;
                this.RaisePropertyChanged("capacidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public estadoMesa estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaModificacionSpecified {
            get {
                return this.fechaModificacionFieldSpecified;
            }
            set {
                this.fechaModificacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaModificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idMesa {
            get {
                return this.idMesaField;
            }
            set {
                this.idMesaField = value;
                this.RaisePropertyChanged("idMesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idMesaSpecified {
            get {
                return this.idMesaFieldSpecified;
            }
            set {
                this.idMesaFieldSpecified = value;
                this.RaisePropertyChanged("idMesaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public localDTO local {
            get {
                return this.localField;
            }
            set {
                this.localField = value;
                this.RaisePropertyChanged("local");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string numeroMesa {
            get {
                return this.numeroMesaField;
            }
            set {
                this.numeroMesaField = value;
                this.RaisePropertyChanged("numeroMesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public tipoMesaDTO tipoMesa {
            get {
                return this.tipoMesaField;
            }
            set {
                this.tipoMesaField = value;
                this.RaisePropertyChanged("tipoMesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string usuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
                this.RaisePropertyChanged("usuarioModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public int x {
            get {
                return this.xField;
            }
            set {
                this.xField = value;
                this.RaisePropertyChanged("x");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool xSpecified {
            get {
                return this.xFieldSpecified;
            }
            set {
                this.xFieldSpecified = value;
                this.RaisePropertyChanged("xSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public int y {
            get {
                return this.yField;
            }
            set {
                this.yField = value;
                this.RaisePropertyChanged("y");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ySpecified {
            get {
                return this.yFieldSpecified;
            }
            set {
                this.yFieldSpecified = value;
                this.RaisePropertyChanged("ySpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public enum estadoMesa {
        
        /// <remarks/>
        DISPONIBLE,
        
        /// <remarks/>
        RESERVADA,
        
        /// <remarks/>
        EN_USO,
        
        /// <remarks/>
        EN_MANTENIMIENTO,
        
        /// <remarks/>
        DESECHADA,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softres.pucp.edu.pe/", ConfigurationName="MesaWSClient.Mesa")]
    public interface Mesa {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Mesa/insertarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Mesa/insertarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.MesaWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Mesa/insertar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.MesaWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Mesa/insertar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.MesaWSClient.insertarResponse insertar(SoftResBusiness.MesaWSClient.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Mesa/insertarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Mesa/insertarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.insertarResponse> insertarAsync(SoftResBusiness.MesaWSClient.insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Mesa/obtenerPorIdRequest", ReplyAction="http://services.softres.pucp.edu.pe/Mesa/obtenerPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.MesaWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Mesa/obtenerPorId/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.MesaWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Mesa/obtenerPorId/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.MesaWSClient.obtenerPorIdResponse obtenerPorId(SoftResBusiness.MesaWSClient.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Mesa/obtenerPorIdRequest", ReplyAction="http://services.softres.pucp.edu.pe/Mesa/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.obtenerPorIdResponse> obtenerPorIdAsync(SoftResBusiness.MesaWSClient.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Mesa/eliminarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Mesa/eliminarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.MesaWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Mesa/eliminar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.MesaWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Mesa/eliminar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.MesaWSClient.eliminarResponse eliminar(SoftResBusiness.MesaWSClient.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Mesa/eliminarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Mesa/eliminarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.eliminarResponse> eliminarAsync(SoftResBusiness.MesaWSClient.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Mesa/modificarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Mesa/modificarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.MesaWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Mesa/modificar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.MesaWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Mesa/modificar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.MesaWSClient.modificarResponse modificar(SoftResBusiness.MesaWSClient.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Mesa/modificarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Mesa/modificarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.modificarResponse> modificarAsync(SoftResBusiness.MesaWSClient.modificarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Mesa/listarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Mesa/listarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.MesaWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Mesa/listar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.MesaWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Mesa/listar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.MesaWSClient.listarResponse listar(SoftResBusiness.MesaWSClient.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Mesa/listarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Mesa/listarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.listarResponse> listarAsync(SoftResBusiness.MesaWSClient.listarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.MesaWSClient.mesaDTO arg0;
        
        public insertarRequest() {
        }
        
        public insertarRequest(SoftResBusiness.MesaWSClient.mesaDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.MesaWSClient.mesaDTO @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(SoftResBusiness.MesaWSClient.mesaDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.MesaWSClient.mesaDTO arg0;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(SoftResBusiness.MesaWSClient.mesaDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.MesaWSClient.mesaDTO arg0;
        
        public modificarRequest() {
        }
        
        public modificarRequest(SoftResBusiness.MesaWSClient.mesaDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarResponse() {
        }
        
        public modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class mesaParametros : object, System.ComponentModel.INotifyPropertyChanged {
        
        private estadoMesa estadoField;
        
        private bool estadoFieldSpecified;
        
        private int idLocalField;
        
        private bool idLocalFieldSpecified;
        
        private int idTipoMesaField;
        
        private bool idTipoMesaFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public estadoMesa estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idLocal {
            get {
                return this.idLocalField;
            }
            set {
                this.idLocalField = value;
                this.RaisePropertyChanged("idLocal");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idLocalSpecified {
            get {
                return this.idLocalFieldSpecified;
            }
            set {
                this.idLocalFieldSpecified = value;
                this.RaisePropertyChanged("idLocalSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idTipoMesa {
            get {
                return this.idTipoMesaField;
            }
            set {
                this.idTipoMesaField = value;
                this.RaisePropertyChanged("idTipoMesa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idTipoMesaSpecified {
            get {
                return this.idTipoMesaFieldSpecified;
            }
            set {
                this.idTipoMesaFieldSpecified = value;
                this.RaisePropertyChanged("idTipoMesaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.MesaWSClient.mesaParametros arg0;
        
        public listarRequest() {
        }
        
        public listarRequest(SoftResBusiness.MesaWSClient.mesaParametros arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.MesaWSClient.mesaDTO[] @return;
        
        public listarResponse() {
        }
        
        public listarResponse(SoftResBusiness.MesaWSClient.mesaDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MesaChannel : SoftResBusiness.MesaWSClient.Mesa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MesaClient : System.ServiceModel.ClientBase<SoftResBusiness.MesaWSClient.Mesa>, SoftResBusiness.MesaWSClient.Mesa {
        
        public MesaClient() {
        }
        
        public MesaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MesaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MesaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.MesaWSClient.insertarResponse SoftResBusiness.MesaWSClient.Mesa.insertar(SoftResBusiness.MesaWSClient.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(SoftResBusiness.MesaWSClient.mesaDTO arg0) {
            SoftResBusiness.MesaWSClient.insertarRequest inValue = new SoftResBusiness.MesaWSClient.insertarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.MesaWSClient.insertarResponse retVal = ((SoftResBusiness.MesaWSClient.Mesa)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.insertarResponse> SoftResBusiness.MesaWSClient.Mesa.insertarAsync(SoftResBusiness.MesaWSClient.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.insertarResponse> insertarAsync(SoftResBusiness.MesaWSClient.mesaDTO arg0) {
            SoftResBusiness.MesaWSClient.insertarRequest inValue = new SoftResBusiness.MesaWSClient.insertarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.MesaWSClient.Mesa)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.MesaWSClient.obtenerPorIdResponse SoftResBusiness.MesaWSClient.Mesa.obtenerPorId(SoftResBusiness.MesaWSClient.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public SoftResBusiness.MesaWSClient.mesaDTO obtenerPorId(int arg0) {
            SoftResBusiness.MesaWSClient.obtenerPorIdRequest inValue = new SoftResBusiness.MesaWSClient.obtenerPorIdRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.MesaWSClient.obtenerPorIdResponse retVal = ((SoftResBusiness.MesaWSClient.Mesa)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.obtenerPorIdResponse> SoftResBusiness.MesaWSClient.Mesa.obtenerPorIdAsync(SoftResBusiness.MesaWSClient.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.obtenerPorIdResponse> obtenerPorIdAsync(int arg0) {
            SoftResBusiness.MesaWSClient.obtenerPorIdRequest inValue = new SoftResBusiness.MesaWSClient.obtenerPorIdRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.MesaWSClient.Mesa)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.MesaWSClient.eliminarResponse SoftResBusiness.MesaWSClient.Mesa.eliminar(SoftResBusiness.MesaWSClient.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(SoftResBusiness.MesaWSClient.mesaDTO arg0) {
            SoftResBusiness.MesaWSClient.eliminarRequest inValue = new SoftResBusiness.MesaWSClient.eliminarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.MesaWSClient.eliminarResponse retVal = ((SoftResBusiness.MesaWSClient.Mesa)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.eliminarResponse> SoftResBusiness.MesaWSClient.Mesa.eliminarAsync(SoftResBusiness.MesaWSClient.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.eliminarResponse> eliminarAsync(SoftResBusiness.MesaWSClient.mesaDTO arg0) {
            SoftResBusiness.MesaWSClient.eliminarRequest inValue = new SoftResBusiness.MesaWSClient.eliminarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.MesaWSClient.Mesa)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.MesaWSClient.modificarResponse SoftResBusiness.MesaWSClient.Mesa.modificar(SoftResBusiness.MesaWSClient.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public int modificar(SoftResBusiness.MesaWSClient.mesaDTO arg0) {
            SoftResBusiness.MesaWSClient.modificarRequest inValue = new SoftResBusiness.MesaWSClient.modificarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.MesaWSClient.modificarResponse retVal = ((SoftResBusiness.MesaWSClient.Mesa)(this)).modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.modificarResponse> SoftResBusiness.MesaWSClient.Mesa.modificarAsync(SoftResBusiness.MesaWSClient.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.modificarResponse> modificarAsync(SoftResBusiness.MesaWSClient.mesaDTO arg0) {
            SoftResBusiness.MesaWSClient.modificarRequest inValue = new SoftResBusiness.MesaWSClient.modificarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.MesaWSClient.Mesa)(this)).modificarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.MesaWSClient.listarResponse SoftResBusiness.MesaWSClient.Mesa.listar(SoftResBusiness.MesaWSClient.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public SoftResBusiness.MesaWSClient.mesaDTO[] listar(SoftResBusiness.MesaWSClient.mesaParametros arg0) {
            SoftResBusiness.MesaWSClient.listarRequest inValue = new SoftResBusiness.MesaWSClient.listarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.MesaWSClient.listarResponse retVal = ((SoftResBusiness.MesaWSClient.Mesa)(this)).listar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.listarResponse> SoftResBusiness.MesaWSClient.Mesa.listarAsync(SoftResBusiness.MesaWSClient.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.MesaWSClient.listarResponse> listarAsync(SoftResBusiness.MesaWSClient.mesaParametros arg0) {
            SoftResBusiness.MesaWSClient.listarRequest inValue = new SoftResBusiness.MesaWSClient.listarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.MesaWSClient.Mesa)(this)).listarAsync(inValue);
        }
    }
}
