//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftResBusiness.SedeWSClient {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class sedeDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string distritoField;
        
        private bool estadoField;
        
        private bool estadoFieldSpecified;
        
        private System.DateTime fechaCreacionField;
        
        private bool fechaCreacionFieldSpecified;
        
        private System.DateTime fechaModificacionField;
        
        private bool fechaModificacionFieldSpecified;
        
        private string horariosField;
        
        private int idSedeField;
        
        private bool idSedeFieldSpecified;
        
        private string nombreField;
        
        private string usuarioCreacionField;
        
        private string usuarioModificacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string distrito {
            get {
                return this.distritoField;
            }
            set {
                this.distritoField = value;
                this.RaisePropertyChanged("distrito");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime fechaCreacion {
            get {
                return this.fechaCreacionField;
            }
            set {
                this.fechaCreacionField = value;
                this.RaisePropertyChanged("fechaCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaCreacionSpecified {
            get {
                return this.fechaCreacionFieldSpecified;
            }
            set {
                this.fechaCreacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaCreacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaModificacion {
            get {
                return this.fechaModificacionField;
            }
            set {
                this.fechaModificacionField = value;
                this.RaisePropertyChanged("fechaModificacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaModificacionSpecified {
            get {
                return this.fechaModificacionFieldSpecified;
            }
            set {
                this.fechaModificacionFieldSpecified = value;
                this.RaisePropertyChanged("fechaModificacionSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string horarios {
            get {
                return this.horariosField;
            }
            set {
                this.horariosField = value;
                this.RaisePropertyChanged("horarios");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSedeSpecified {
            get {
                return this.idSedeFieldSpecified;
            }
            set {
                this.idSedeFieldSpecified = value;
                this.RaisePropertyChanged("idSedeSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string usuarioCreacion {
            get {
                return this.usuarioCreacionField;
            }
            set {
                this.usuarioCreacionField = value;
                this.RaisePropertyChanged("usuarioCreacion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string usuarioModificacion {
            get {
                return this.usuarioModificacionField;
            }
            set {
                this.usuarioModificacionField = value;
                this.RaisePropertyChanged("usuarioModificacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softres.pucp.edu.pe/", ConfigurationName="SedeWSClient.Sede")]
    public interface Sede {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Sede/insertarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Sede/insertarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.SedeWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Sede/insertar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.SedeWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Sede/insertar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.SedeWSClient.insertarResponse insertar(SoftResBusiness.SedeWSClient.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Sede/insertarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Sede/insertarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.insertarResponse> insertarAsync(SoftResBusiness.SedeWSClient.insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Sede/obtenerPorIdRequest", ReplyAction="http://services.softres.pucp.edu.pe/Sede/obtenerPorIdResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.SedeWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Sede/obtenerPorId/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.SedeWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Sede/obtenerPorId/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.SedeWSClient.obtenerPorIdResponse obtenerPorId(SoftResBusiness.SedeWSClient.obtenerPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Sede/obtenerPorIdRequest", ReplyAction="http://services.softres.pucp.edu.pe/Sede/obtenerPorIdResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.obtenerPorIdResponse> obtenerPorIdAsync(SoftResBusiness.SedeWSClient.obtenerPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Sede/eliminarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Sede/eliminarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.SedeWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Sede/eliminar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.SedeWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Sede/eliminar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.SedeWSClient.eliminarResponse eliminar(SoftResBusiness.SedeWSClient.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Sede/eliminarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Sede/eliminarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.eliminarResponse> eliminarAsync(SoftResBusiness.SedeWSClient.eliminarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Sede/listarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Sede/listarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.SedeWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Sede/listar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.SedeWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Sede/listar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.SedeWSClient.listarResponse listar(SoftResBusiness.SedeWSClient.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Sede/listarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Sede/listarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.listarResponse> listarAsync(SoftResBusiness.SedeWSClient.listarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Sede/modificarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Sede/modificarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.SedeWSClient.IOException), Action="http://services.softres.pucp.edu.pe/Sede/modificar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.SedeWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/Sede/modificar/Fault/InterruptedException", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.SedeWSClient.modificarResponse modificar(SoftResBusiness.SedeWSClient.modificarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/Sede/modificarRequest", ReplyAction="http://services.softres.pucp.edu.pe/Sede/modificarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.modificarResponse> modificarAsync(SoftResBusiness.SedeWSClient.modificarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.SedeWSClient.sedeDTO arg0;
        
        public insertarRequest() {
        }
        
        public insertarRequest(SoftResBusiness.SedeWSClient.sedeDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorId", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public obtenerPorIdRequest() {
        }
        
        public obtenerPorIdRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPorIdResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class obtenerPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.SedeWSClient.sedeDTO @return;
        
        public obtenerPorIdResponse() {
        }
        
        public obtenerPorIdResponse(SoftResBusiness.SedeWSClient.sedeDTO @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.SedeWSClient.sedeDTO arg0;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(SoftResBusiness.SedeWSClient.sedeDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class sedeParametros : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool estadoField;
        
        private bool estadoFieldSpecified;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool estado {
            get {
                return this.estadoField;
            }
            set {
                this.estadoField = value;
                this.RaisePropertyChanged("estado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estadoSpecified {
            get {
                return this.estadoFieldSpecified;
            }
            set {
                this.estadoFieldSpecified = value;
                this.RaisePropertyChanged("estadoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.SedeWSClient.sedeParametros arg0;
        
        public listarRequest() {
        }
        
        public listarRequest(SoftResBusiness.SedeWSClient.sedeParametros arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.SedeWSClient.sedeDTO[] @return;
        
        public listarResponse() {
        }
        
        public listarResponse(SoftResBusiness.SedeWSClient.sedeDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.SedeWSClient.sedeDTO arg0;
        
        public modificarRequest() {
        }
        
        public modificarRequest(SoftResBusiness.SedeWSClient.sedeDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class modificarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarResponse() {
        }
        
        public modificarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SedeChannel : SoftResBusiness.SedeWSClient.Sede, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SedeClient : System.ServiceModel.ClientBase<SoftResBusiness.SedeWSClient.Sede>, SoftResBusiness.SedeWSClient.Sede {
        
        public SedeClient() {
        }
        
        public SedeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SedeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SedeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SedeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.SedeWSClient.insertarResponse SoftResBusiness.SedeWSClient.Sede.insertar(SoftResBusiness.SedeWSClient.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(SoftResBusiness.SedeWSClient.sedeDTO arg0) {
            SoftResBusiness.SedeWSClient.insertarRequest inValue = new SoftResBusiness.SedeWSClient.insertarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.SedeWSClient.insertarResponse retVal = ((SoftResBusiness.SedeWSClient.Sede)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.insertarResponse> SoftResBusiness.SedeWSClient.Sede.insertarAsync(SoftResBusiness.SedeWSClient.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.insertarResponse> insertarAsync(SoftResBusiness.SedeWSClient.sedeDTO arg0) {
            SoftResBusiness.SedeWSClient.insertarRequest inValue = new SoftResBusiness.SedeWSClient.insertarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.SedeWSClient.Sede)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.SedeWSClient.obtenerPorIdResponse SoftResBusiness.SedeWSClient.Sede.obtenerPorId(SoftResBusiness.SedeWSClient.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorId(request);
        }
        
        public SoftResBusiness.SedeWSClient.sedeDTO obtenerPorId(int arg0) {
            SoftResBusiness.SedeWSClient.obtenerPorIdRequest inValue = new SoftResBusiness.SedeWSClient.obtenerPorIdRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.SedeWSClient.obtenerPorIdResponse retVal = ((SoftResBusiness.SedeWSClient.Sede)(this)).obtenerPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.obtenerPorIdResponse> SoftResBusiness.SedeWSClient.Sede.obtenerPorIdAsync(SoftResBusiness.SedeWSClient.obtenerPorIdRequest request) {
            return base.Channel.obtenerPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.obtenerPorIdResponse> obtenerPorIdAsync(int arg0) {
            SoftResBusiness.SedeWSClient.obtenerPorIdRequest inValue = new SoftResBusiness.SedeWSClient.obtenerPorIdRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.SedeWSClient.Sede)(this)).obtenerPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.SedeWSClient.eliminarResponse SoftResBusiness.SedeWSClient.Sede.eliminar(SoftResBusiness.SedeWSClient.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(SoftResBusiness.SedeWSClient.sedeDTO arg0) {
            SoftResBusiness.SedeWSClient.eliminarRequest inValue = new SoftResBusiness.SedeWSClient.eliminarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.SedeWSClient.eliminarResponse retVal = ((SoftResBusiness.SedeWSClient.Sede)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.eliminarResponse> SoftResBusiness.SedeWSClient.Sede.eliminarAsync(SoftResBusiness.SedeWSClient.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.eliminarResponse> eliminarAsync(SoftResBusiness.SedeWSClient.sedeDTO arg0) {
            SoftResBusiness.SedeWSClient.eliminarRequest inValue = new SoftResBusiness.SedeWSClient.eliminarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.SedeWSClient.Sede)(this)).eliminarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.SedeWSClient.listarResponse SoftResBusiness.SedeWSClient.Sede.listar(SoftResBusiness.SedeWSClient.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public SoftResBusiness.SedeWSClient.sedeDTO[] listar(SoftResBusiness.SedeWSClient.sedeParametros arg0) {
            SoftResBusiness.SedeWSClient.listarRequest inValue = new SoftResBusiness.SedeWSClient.listarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.SedeWSClient.listarResponse retVal = ((SoftResBusiness.SedeWSClient.Sede)(this)).listar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.listarResponse> SoftResBusiness.SedeWSClient.Sede.listarAsync(SoftResBusiness.SedeWSClient.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.listarResponse> listarAsync(SoftResBusiness.SedeWSClient.sedeParametros arg0) {
            SoftResBusiness.SedeWSClient.listarRequest inValue = new SoftResBusiness.SedeWSClient.listarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.SedeWSClient.Sede)(this)).listarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.SedeWSClient.modificarResponse SoftResBusiness.SedeWSClient.Sede.modificar(SoftResBusiness.SedeWSClient.modificarRequest request) {
            return base.Channel.modificar(request);
        }
        
        public int modificar(SoftResBusiness.SedeWSClient.sedeDTO arg0) {
            SoftResBusiness.SedeWSClient.modificarRequest inValue = new SoftResBusiness.SedeWSClient.modificarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.SedeWSClient.modificarResponse retVal = ((SoftResBusiness.SedeWSClient.Sede)(this)).modificar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.modificarResponse> SoftResBusiness.SedeWSClient.Sede.modificarAsync(SoftResBusiness.SedeWSClient.modificarRequest request) {
            return base.Channel.modificarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.SedeWSClient.modificarResponse> modificarAsync(SoftResBusiness.SedeWSClient.sedeDTO arg0) {
            SoftResBusiness.SedeWSClient.modificarRequest inValue = new SoftResBusiness.SedeWSClient.modificarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.SedeWSClient.Sede)(this)).modificarAsync(inValue);
        }
    }
}
