//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftResBusiness.HorarioxSedeWSClient {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class IOException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class horariosxSedesDTO : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int idHorarioField;
        
        private bool idHorarioFieldSpecified;
        
        private int idSedeField;
        
        private bool idSedeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public int idHorario {
            get {
                return this.idHorarioField;
            }
            set {
                this.idHorarioField = value;
                this.RaisePropertyChanged("idHorario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idHorarioSpecified {
            get {
                return this.idHorarioFieldSpecified;
            }
            set {
                this.idHorarioFieldSpecified = value;
                this.RaisePropertyChanged("idHorarioSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idSede {
            get {
                return this.idSedeField;
            }
            set {
                this.idSedeField = value;
                this.RaisePropertyChanged("idSede");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSedeSpecified {
            get {
                return this.idSedeFieldSpecified;
            }
            set {
                this.idSedeFieldSpecified = value;
                this.RaisePropertyChanged("idSedeSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://services.softres.pucp.edu.pe/")]
    public partial class InterruptedException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://services.softres.pucp.edu.pe/", ConfigurationName="HorarioxSedeWSClient.HorarioxSede")]
    public interface HorarioxSede {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/HorarioxSede/insertarRequest", ReplyAction="http://services.softres.pucp.edu.pe/HorarioxSede/insertarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.HorarioxSedeWSClient.IOException), Action="http://services.softres.pucp.edu.pe/HorarioxSede/insertar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.HorarioxSedeWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/HorarioxSede/insertar/Fault/InterruptedExcept" +
            "ion", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.HorarioxSedeWSClient.insertarResponse insertar(SoftResBusiness.HorarioxSedeWSClient.insertarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/HorarioxSede/insertarRequest", ReplyAction="http://services.softres.pucp.edu.pe/HorarioxSede/insertarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.HorarioxSedeWSClient.insertarResponse> insertarAsync(SoftResBusiness.HorarioxSedeWSClient.insertarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/HorarioxSede/listarRequest", ReplyAction="http://services.softres.pucp.edu.pe/HorarioxSede/listarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.HorarioxSedeWSClient.IOException), Action="http://services.softres.pucp.edu.pe/HorarioxSede/listar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.HorarioxSedeWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/HorarioxSede/listar/Fault/InterruptedExceptio" +
            "n", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.HorarioxSedeWSClient.listarResponse listar(SoftResBusiness.HorarioxSedeWSClient.listarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/HorarioxSede/listarRequest", ReplyAction="http://services.softres.pucp.edu.pe/HorarioxSede/listarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.HorarioxSedeWSClient.listarResponse> listarAsync(SoftResBusiness.HorarioxSedeWSClient.listarRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/HorarioxSede/eliminarRequest", ReplyAction="http://services.softres.pucp.edu.pe/HorarioxSede/eliminarResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.HorarioxSedeWSClient.IOException), Action="http://services.softres.pucp.edu.pe/HorarioxSede/eliminar/Fault/IOException", Name="IOException")]
        [System.ServiceModel.FaultContractAttribute(typeof(SoftResBusiness.HorarioxSedeWSClient.InterruptedException), Action="http://services.softres.pucp.edu.pe/HorarioxSede/eliminar/Fault/InterruptedExcept" +
            "ion", Name="InterruptedException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftResBusiness.HorarioxSedeWSClient.eliminarResponse eliminar(SoftResBusiness.HorarioxSedeWSClient.eliminarRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://services.softres.pucp.edu.pe/HorarioxSede/eliminarRequest", ReplyAction="http://services.softres.pucp.edu.pe/HorarioxSede/eliminarResponse")]
        System.Threading.Tasks.Task<SoftResBusiness.HorarioxSedeWSClient.eliminarResponse> eliminarAsync(SoftResBusiness.HorarioxSedeWSClient.eliminarRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO arg0;
        
        public insertarRequest() {
        }
        
        public insertarRequest(SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class insertarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarResponse() {
        }
        
        public insertarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public listarRequest() {
        }
        
        public listarRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class listarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO[] @return;
        
        public listarResponse() {
        }
        
        public listarResponse(SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminar", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO arg0;
        
        public eliminarRequest() {
        }
        
        public eliminarRequest(SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarResponse", WrapperNamespace="http://services.softres.pucp.edu.pe/", IsWrapped=true)]
    public partial class eliminarResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://services.softres.pucp.edu.pe/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarResponse() {
        }
        
        public eliminarResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface HorarioxSedeChannel : SoftResBusiness.HorarioxSedeWSClient.HorarioxSede, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class HorarioxSedeClient : System.ServiceModel.ClientBase<SoftResBusiness.HorarioxSedeWSClient.HorarioxSede>, SoftResBusiness.HorarioxSedeWSClient.HorarioxSede {
        
        public HorarioxSedeClient() {
        }
        
        public HorarioxSedeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public HorarioxSedeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioxSedeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public HorarioxSedeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.HorarioxSedeWSClient.insertarResponse SoftResBusiness.HorarioxSedeWSClient.HorarioxSede.insertar(SoftResBusiness.HorarioxSedeWSClient.insertarRequest request) {
            return base.Channel.insertar(request);
        }
        
        public int insertar(SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO arg0) {
            SoftResBusiness.HorarioxSedeWSClient.insertarRequest inValue = new SoftResBusiness.HorarioxSedeWSClient.insertarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.HorarioxSedeWSClient.insertarResponse retVal = ((SoftResBusiness.HorarioxSedeWSClient.HorarioxSede)(this)).insertar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.HorarioxSedeWSClient.insertarResponse> SoftResBusiness.HorarioxSedeWSClient.HorarioxSede.insertarAsync(SoftResBusiness.HorarioxSedeWSClient.insertarRequest request) {
            return base.Channel.insertarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.HorarioxSedeWSClient.insertarResponse> insertarAsync(SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO arg0) {
            SoftResBusiness.HorarioxSedeWSClient.insertarRequest inValue = new SoftResBusiness.HorarioxSedeWSClient.insertarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.HorarioxSedeWSClient.HorarioxSede)(this)).insertarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.HorarioxSedeWSClient.listarResponse SoftResBusiness.HorarioxSedeWSClient.HorarioxSede.listar(SoftResBusiness.HorarioxSedeWSClient.listarRequest request) {
            return base.Channel.listar(request);
        }
        
        public SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO[] listar(int arg0) {
            SoftResBusiness.HorarioxSedeWSClient.listarRequest inValue = new SoftResBusiness.HorarioxSedeWSClient.listarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.HorarioxSedeWSClient.listarResponse retVal = ((SoftResBusiness.HorarioxSedeWSClient.HorarioxSede)(this)).listar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.HorarioxSedeWSClient.listarResponse> SoftResBusiness.HorarioxSedeWSClient.HorarioxSede.listarAsync(SoftResBusiness.HorarioxSedeWSClient.listarRequest request) {
            return base.Channel.listarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.HorarioxSedeWSClient.listarResponse> listarAsync(int arg0) {
            SoftResBusiness.HorarioxSedeWSClient.listarRequest inValue = new SoftResBusiness.HorarioxSedeWSClient.listarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.HorarioxSedeWSClient.HorarioxSede)(this)).listarAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftResBusiness.HorarioxSedeWSClient.eliminarResponse SoftResBusiness.HorarioxSedeWSClient.HorarioxSede.eliminar(SoftResBusiness.HorarioxSedeWSClient.eliminarRequest request) {
            return base.Channel.eliminar(request);
        }
        
        public int eliminar(SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO arg0) {
            SoftResBusiness.HorarioxSedeWSClient.eliminarRequest inValue = new SoftResBusiness.HorarioxSedeWSClient.eliminarRequest();
            inValue.arg0 = arg0;
            SoftResBusiness.HorarioxSedeWSClient.eliminarResponse retVal = ((SoftResBusiness.HorarioxSedeWSClient.HorarioxSede)(this)).eliminar(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftResBusiness.HorarioxSedeWSClient.eliminarResponse> SoftResBusiness.HorarioxSedeWSClient.HorarioxSede.eliminarAsync(SoftResBusiness.HorarioxSedeWSClient.eliminarRequest request) {
            return base.Channel.eliminarAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftResBusiness.HorarioxSedeWSClient.eliminarResponse> eliminarAsync(SoftResBusiness.HorarioxSedeWSClient.horariosxSedesDTO arg0) {
            SoftResBusiness.HorarioxSedeWSClient.eliminarRequest inValue = new SoftResBusiness.HorarioxSedeWSClient.eliminarRequest();
            inValue.arg0 = arg0;
            return ((SoftResBusiness.HorarioxSedeWSClient.HorarioxSede)(this)).eliminarAsync(inValue);
        }
    }
}
